packages_location = "~/packages.vurf"
default_section = "default"

[[sections]]
name = "default"
install = "echo Install this:"
uninstall = "echo Install this:"
sequential = True

[parameters]
you_excited = true
day = "best"
